CREATE TABLE tb_pelanggan (
	no_ktp VARCHAR(20) PRIMARY KEY,
	nama_pelanggan VARCHAR(100) NOT NULL DEFAULT(''),
	no_hp VARCHAR(20) NOT NULL DEFAULT(''),
    alamat VARCHAR(225) NOT NULL DEFAULT(''),
	email VARCHAR(50) NOT NULL DEFAULT(''),
	password VARCHAR(225) NOT NULL DEFAULT(''),
	created_at DATETIME DEFAULT GETDATE(),
	updated_at DATETIME DEFAULT GETDATE()
	);